### ISSUE TITLE
Pretrained Model of GPT2

### ISSUE THREAD

**Issue by ToheartZhang** [LYH-YF/MWPToolkit#5]
Thanks for your great work. I noticed that the default pretrained model path in GPT2 is `pretrained/gpt2_cn`, which is ignored in .gitignore. Could you provide a download link for the Chinese model?

**Comment by LYH-YF** [comment]
Thanks for your support. 

We ran GPT2 with pretrained model ```uer/gpt2-base-chinese-cluecorpussmall``` 'https://huggingface.co/uer/gpt2-chinese-cluecorpussmall' for Chinese datasets, and ```gpt2``` 'https://huggingface.co/gpt2' for English datasets. 

It's not necessary for you to download model into ```pretrained/gpt2_cn``` and just input ```--pretrained_model_path=uer/gpt2-base-chinese-cluecorpussmall```  in command line to cover default pretrained model path.

I hope this will help you.

**Comment by ToheartZhang** [comment]
Thanks for your reply and your great work again.
