### ISSUE TITLE
what is the Chinese pretrained-transformers used in the paper?

### ISSUE THREAD

**Issue by allanj** [LYH-YF/MWPToolkit#6]
Thanks for the great work. Just wonder for the pre-trained Roberta-gen (Chinese version), which one do you use in the experiments for math23k.

**Comment by LYH-YF** [comment]
Roberta for Chinese datasets, ```uer/chinese_roberta_L-12_H-768``` https://huggingface.co/uer/chinese_roberta_L-12_H-768.

Bert for Chinese datasets, ```bert-base-chinese``` https://huggingface.co/bert-base-chinese.

GPT2 for Chinese datasets, ```uer/gpt2-base-chinese-cluecorpussmall``` https://huggingface.co/uer/gpt2-chinese-cluecorpussmall.

Thanks for your support!
