### ISSUE TITLE
Are you able to reproduce the paper results from MWP-BERT (Liang et al., 2021)

### ISSUE THREAD

**Issue by allanj** [LYH-YF/MWPToolkit#7]
I found that the paper (https://arxiv.org/pdf/2107.13435.pdf) was also using the BERT-based model, but it seems they are able to achieve 83.8 accuracy (Table 1 in the paper, MWP-BERT w/o MLM), by a simple sequence-to-sequence model, their paper mentioned it is a sequence-to-tree. But from the figure, it seems it is still generating a sequence only.

![image](https://user-images.githubusercontent.com/3351187/132995217-293a1fd1-c828-4b46-ba35-ec682ee05925.png)

I notice that you also mentioned this work in the related work. Just wonder if you guys have replicated that that results as well.

**Comment by allanj** [comment]
Also, what's the difference between their approach and the BERTGen/RobertaGen model in MWPToolkit paper?

**Comment by demoleiwang** [comment]
> Also, what's the difference between their approach and the BERTGen/RobertaGen model in MWPToolkit paper?

Hi, allanj. They are different. For BERTGen, You can refer to  Logical Natural Language Generation from Open-Domain Tables and its corresponding Github repo: https://github.com/wenhuchen/LogicNLG. In short, the encoder of BERTGen is the normal BERT model and the decoder is the normal Transformer decoder. However, MWP-BERT uses the normal BERT as the encoder and tree decoder of GTS as the decoder with 5 beam search. As shown in our experimental table, you can see normal Transformer is significantly worse than GTS. It may help you understand why MWP-BERT is better than BERTGen.

**Comment by demoleiwang** [comment]
We will do our best to reproduce MWP-BERT in the next few days.

**Comment by allanj** [comment]
Thanks a lot for the comments.

**Comment by devroy73** [comment]
Hi Has this been implemented? Thanks in advance
