### ISSUE TITLE
MAWPS dataset issue

### ISSUE THREAD

**Issue by allanj** [LYH-YF/MWPToolkit#9]
In the graph-to-tree paper, they reported the size of MAWPS is 2373, but in this toolkit/paper, the size is 1987. Which one is correct? And also, it might not be comparable for this table.

![image](https://user-images.githubusercontent.com/3351187/136646871-319cf643-fbbf-4f94-84f8-da7afbaabe74.png)

**Comment by allanj** [comment]
any updates on this?

**Comment by LYH-YF** [comment]
The size of mawps full set is 2373, but in the official code of graph2tree https://github.com/2003pro/Graph2Tree, they extract a subset and they don't mention it in the paper.

You can see that the size of it is 1921(this is a screen shot while running official code). And you can find the code to extract subset easily.
![05%YVTY@73`AC}RA }C$MI](https://user-images.githubusercontent.com/63840506/138981068-fa9e4c4b-2c64-448b-83c4-4ddb5023a176.png)

We extract a subset of mawps named mawps-single with similar code. And it's more comparable than full set with the official result

We also prepare to public mawps full set and update some results on it.

**Comment by allanj** [comment]
Thanks for the reply. It is helpful.
